"""empty message

Revision ID: 9dd922bedeee
Revises: 714950a9a3c7
Create Date: 2024-02-18 12:04:18.027456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd922bedeee'
down_revision = '714950a9a3c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_supbi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('codigos_supbi', schema=None) as batch_op:
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###
