"""empty message

Revision ID: dc934298794b
Revises: 710c9c726ac2
Create Date: 2024-03-18 17:04:25.132685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc934298794b'
down_revision = '710c9c726ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('last_updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_gastos_created_on'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_gastos_last_updated_on'), ['last_updated_on'], unique=False)

    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('last_updated_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.create_index(batch_op.f('ix_ingresos_created_on'), ['created_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingresos_last_updated_on'), ['last_updated_on'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.alter_column('saldo_actual',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('saldo_actual',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingresos_last_updated_on'))
        batch_op.drop_index(batch_op.f('ix_ingresos_created_on'))
        batch_op.drop_column('last_updated_on')
        batch_op.drop_column('created_on')

    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gastos_last_updated_on'))
        batch_op.drop_index(batch_op.f('ix_gastos_created_on'))
        batch_op.drop_column('last_updated_on')
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###
